# Generated by Django 2.0.2 on 2018-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlemsgboard',
            name='msg_pickle_str',
            field=models.BinaryField(max_length=100000),
        ),
    ]
