# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171209_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='level',
        ),
    ]
