# Generated by Django 2.0.2 on 2018-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180303_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikeMeCount', models.IntegerField()),
                ('UnLikeMeCount', models.IntegerField()),
            ],
        ),
    ]
