# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171129_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlemsgboard',
            name='msg_pickle_str',
            field=models.CharField(max_length=20000),
        ),
    ]
