# Generated by Django 2.0.2 on 2018-03-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_likemedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_exist',
            field=models.IntegerField(default=1),
        ),
    ]
