# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171129_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlemsgboard',
            name='msg_pickle_str',
        ),
    ]
